apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:blue
    ports:
    - containerPort: 80
  tolerations:
  - key: disktype
    operator: Equal
    value: slow
    effect: NoSchedule